name: Build MDCx Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone external repository
        run: |
          git clone https://github.com/sqzw-x/mdcx.git
          cd mdcx
          git fetch --tags
          git checkout 120250810

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd mdcx
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make build.sh executable
        run: chmod +x mdcx/scripts/build.sh

      - name: Build app
        run: |
          cd mdcx
          ./scripts/build.sh

      - name: Rename output EXE to MDCx
        run: |
          cd mdcx/dist
          exe_file=$(ls *.exe | head -n 1)
          echo "Found exe: $exe_file"
          mv "$exe_file" MDCx

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MDCx_120250810
          path: mdcx/dist/MDCx
          compression-level: 0
