name: Build MDCx Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed to fetch tags

      - name: Checkout target tag
        run: |
          git fetch --tags
          git checkout 120250810

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make build.sh executable
        run: chmod +x scripts/build.sh

      - name: Build app
        run: ./scripts/build.sh

      - name: Rename output EXE to MDCx
        run: |
          cd dist
          exe_file=$(ls *.exe | head -n 1)
          echo "Found exe: $exe_file"
          mv "$exe_file" MDCx

      - name: Zip MDCx
        run: |
          cd dist
          zip -r MDCx_120250810.zip MDCx

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MDCx_120250810
          path: dist/MDCx_120250810.zip
          compression-level: 0
